name: nashik
description: "A new Flutter project."


publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  animated_text_kit: ^4.2.2
  awesome_snackbar_content_new: ^0.1.2
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.4
  curved_navigation_bar: ^1.0.6
  custom_rating_bar: ^3.0.0
  dio: ^5.7.0
  equatable: ^2.0.5
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  fpdart: ^1.1.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get_it: ^8.0.0
  getwidget: ^4.0.0
  go_router: ^14.2.8
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hydrated_bloc: ^9.1.5
  icons_launcher: ^3.0.0
  icons_plus: ^5.0.0
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  introduction_screen: ^3.1.14
  loading_overlay: ^0.3.0
  lottie: ^3.1.2
  mongo_dart: ^0.10.3
  package_rename: ^1.7.1
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  rflutter_alert: ^2.0.7
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  sn_progress_dialog: ^1.1.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #   - assets/icons/
  #   - assets/images/
  #   - assets/images/onboarding/
  #   - assets/logo/
  #   - assets/lottie/
  #   - assets/svg/
  #   - assets/